### ISSUE TITLE
jaword-forward moves too far in some cases

### ISSUE THREAD

**Issue by knu** [zk-phi/jaword#3]
Here's an example.  The `_` symbol signifies the cursor.

Before:
```
_
a b c 1
```
After:
```

a b c_1
```
Expected:
```

a_b c 1
```

Looks like this happens when the line has only space characters after the point.

**Comment by zk-phi** [comment]
fixed.
jaword has been used regexp "[\s\t\n]*\\Ca" (= a non-ascii character after zero or more spaces) to decide whether to use the built-in "forward-word" function or the segmenter, but it unexpectedly matches "\n".
now jaword uses `(save-excursion (skip-chars-forward "\s\t\n") (looking-at "\\Ca"))` to do it.
thanks.

**Comment by knu** [comment]
Cool, thanks!
