### ISSUE TITLE
jaword-backward jumps back too far in some cases

### ISSUE THREAD

**Issue by knu** [zk-phi/jaword#4]
When the point is at the end of `右の図1`, invoking `jaword-backward` takes the point back to the top of the whole phrase, where I expect it would stop at `1`.

Could this be fixed?

**Comment by zk-phi** [comment]
`jaword-backward` internally uses `subword-backward` in the case, and `subword-backward` seems to jump too far.
so we can probably fix the problem by implementing a similar function but aware of word boundary between japanese and non-japanese words.

**Comment by knu** [comment]
Right, I forgot to tell jaword-enable-subword was turned on and this indeed looks like a "bug" of `subword-backward`.
I should perhaps monkey-patch `subword-backward` as follows:
```
(defadvice subword-backward
    (around fix activate)
  (interactive "^p")
  (goto-char (max (save-excursion (backward-word arg) (point))
                  (save-excursion ad-do-it (point)))))
```

**Comment by zk-phi** [comment]
thanks, I'll take the approach.
